// <auto-generated />
using System;
using AIAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIAPI.Migrations
{
    [DbContext(typeof(SensoringDbContext))]
    [Migration("20260618101033_AddBoundingBoxes")]
    partial class AddBoundingBoxes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AIAPI.Models.BoundingBox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("CenterX")
                        .HasColumnType("real");

                    b.Property<float>("CenterY")
                        .HasColumnType("real");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainingImageId")
                        .HasColumnType("int");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("TrainingImageId");

                    b.ToTable("BoundingBoxes");
                });

            modelBuilder.Entity("AIAPI.Models.Detection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float?>("BoundingBoxCenter")
                        .HasColumnType("real");

                    b.Property<float?>("BoundingBoxLB")
                        .HasColumnType("real");

                    b.Property<float?>("BoundingBoxRB")
                        .HasColumnType("real");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<string>("ImageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("LocatieX")
                        .HasColumnType("float");

                    b.Property<double?>("LocatieY")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Detections");
                });

            modelBuilder.Entity("AIAPI.Models.TrainingImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TrainingImages");
                });

            modelBuilder.Entity("AIAPI.Models.BoundingBox", b =>
                {
                    b.HasOne("AIAPI.Models.TrainingImage", "TrainingImage")
                        .WithMany("BoundingBoxes")
                        .HasForeignKey("TrainingImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingImage");
                });

            modelBuilder.Entity("AIAPI.Models.TrainingImage", b =>
                {
                    b.Navigation("BoundingBoxes");
                });
#pragma warning restore 612, 618
        }
    }
}
